apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
  name: nodeless-cost-calculator
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: nodeless-cost-calculator
      - name: redis
      - name: cloudinfo
      containers:
      - $setElementOrder/env:
        - name: CLOUD_PROVIDER
        - name: REGION
        env:
        - name: CLOUD_PROVIDER
          value: gce
        - name: REGION
          value: "us-east1"
        image: elotl/nodeless-cost-calculator
        name: nodeless-cost-calculator
      - name: cloudinfo
        readinessProbe:
          httpGet:
            path: /api/v1/providers/google/services/compute/regions/us-east1/products
