apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
secretGenerator:
  - name: cloudinfo-config
    behavior: replace
    files:
      - config.toml
patchesStrategicMerge:
- deployment.yaml
