apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
  name: nodeless-cost-calculator
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: nodeless-cost-calculator
        image: elotl/nodeless-cost-calculator:v0.0.3-55-g1a4a19e-dirty
        env:
        - name: CLOUD_PROVIDER
          value: aws
        - name: REGION
          value: us-east-1
        - name: REDIS_HOST
          value: redis
