---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cost-calculator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cost-calculator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cost-calculator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cost-calculator
subjects:
- kind: ServiceAccount
  name: cost-calculator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-calculator
spec:
  selector:
    matchLabels:
      run: cost-calculator
  replicas: 1
  template:
    metadata:
      labels:
        run: cost-calculator
    spec:
      serviceAccount: cost-calculator
      serviceAccountName: cost-calculator
      containers:
        - name: cost-calculator
          image: 689494258501.dkr.ecr.us-east-1.amazonaws.com/elotl/cost-calculator:e2e0a29
          ports:
            - containerPort: 5000
              protocol: TCP
