---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeless-cost-calculator
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeless-cost-calculator
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodeless-cost-calculator
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodeless-cost-calculator
subjects:
- kind: ServiceAccount
  name: nodeless-cost-calculator
  namespace: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeless-cost-calculator
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
spec:
  selector:
    matchLabels:
      run: nodeless-cost-calculator
  replicas: 1
  template:
    metadata:
      namespace: ${NAMESPACE}
      labels:
        run: nodeless-cost-calculator
        app.kubernetes.io/name: nodeless-cost-calculator
    spec:
      serviceAccount: nodeless-cost-calculator
      serviceAccountName: nodeless-cost-calculator
      containers:
        - name: nodeless-cost-calculator
          image: elotl/nodeless-cost-calculator:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: CLOUD_PROVIDER
              value: ${CLOUD_PROVIDER}
            - name: REGION
              value: ${REGION}
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
        - name: cloudinfo
          image: banzaicloud/cloudinfo
          env:
            - name: CLOUDINFO_LOG_FORMAT
              value: text
#            - name: CLOUDINFO_PROVIDER_AZURE_ENABLED
#              value: "true"
#            - name: AZURE_SUBSCRIPTION_ID
#              value: set your sub id here
#            - name: AZURE_TENANT_ID
#              value: set your tenant id here
#            - name: AZURE_CLIENT_ID
#              value: set your client id here
#            - name: AZURE_CLIENT_SECRET
#              value: set your client secret here
            - name: CLOUDINFO_STORE_REDIS_ENABLED
              value: "true"
          ports:
            - containerPort: 8000
              protocol: TCP
#          readinessProbe:
#            httpGet:
#              port: 8000
#               you need to set provider (azure, amazon, goole) and region here
#              path: /api/v1/providers/azure/services/compute/regions/eastus/products
#            initialDelaySeconds: 120
#            periodSeconds: 60
#            timeoutSeconds: 1200