apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: nodeless-cost-calculator
secretGenerator:
  - name: cloudinfo-config
    files:
      - config.toml
resources:
- deployment.yaml
- rbac.yaml
