---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeless-cost-calculator
  namespace: default
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeless-cost-calculator
  namespace: default
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodeless-cost-calculator
  namespace: default
  labels:
    app.kubernetes.io/name: nodeless-cost-calculator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodeless-cost-calculator
subjects:
- kind: ServiceAccount
  name: nodeless-cost-calculator
  namespace: default
---